services:
  audit-server:
    image: nginx:alpine
    container_name: audit-server
    volumes:
      - /home/damswallace/docker/audits-nginx/audits:/usr/share/nginx/html:ro
      - /home/damswallace/docker/audits-nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    expose:
      - "80"  # Pas de publication sur le host
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      br-dams:
        ipv4_address: 172.18.0.133
    labels:
      - "traefik.enable=true"
      # ROUTEUR
      - "traefik.http.routers.audit-server.rule=Host(`audit.damswallace.fr`)"
      - "traefik.http.routers.audit-server.entrypoints=websecure"
      - "traefik.http.routers.audit-server.tls=true"
      # SERVICE
      - "traefik.http.services.audit-server.loadbalancer.server.port=80"
      # (OPTIONNEL) MIDDLEWARE IP WHITELIST uniquement pour HA
      - "traefik.http.routers.audit-server.middlewares=geoblock@file"
networks:
   br-dams:
     external: true
