services:
  audit-server:
    image: node:20-alpine
    container_name: audit-server
    working_dir: /app
    command: ["node", "server.js"]
    environment:
      - PORT=8080
      - TZ=Europe/Paris
    volumes:
      # Monte tout le projet (server.js, audits/, scripts, etc.)
      - /home/damswallace/docker/audits-nginx:/app
    expose:
      - "8080"   # pas de publication sur le host, Traefik s'y connecte en interne
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      br-dams:
        ipv4_address: 172.18.0.133
    labels:
      - "traefik.enable=true"
      # ROUTEUR
      - "traefik.http.routers.audit-server.rule=Host(`audit.damswallace.fr`)"
      - "traefik.http.routers.audit-server.entrypoints=websecure"
      - "traefik.http.routers.audit-server.tls=true"
      # SERVICE -> port interne du Node server
      - "traefik.http.services.audit-server.loadbalancer.server.port=8080"
      # (optionnel) middleware
      - "traefik.http.routers.audit-server.middlewares=geoblock@file"

networks:
  br-dams:
    external: true
